title: BabyCAT
name: Iva Laginja
description: "Coronagraph demonstration testbed: Learn, Build, and Experiment"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
include: ["_pages"]
logo: "/assets/images/logo.jpeg"
enable_copy_code_button: true
